# Models package
# Import all models for easy access

from __future__ import annotations

from .agents import Agent, AgentInteraction
from .ai_conversations import AIConversation, AIConversationMessage
from .blogs import BlogCategory, BlogPost, BlogPostCategory, BlogPostTag, BlogTag
from .bookings import Booking
from .conversations import Conversation, ConversationParticipant, Message
from .core import FAQ, AppVersion, BugReport, Page
from .data_hub import (
    AuctionAlert,
    BankAuction,
    BankRate,
    CircleRate,
    ColonyApproval,
    CourtAuction,
    GazetteNotification,
    JamabandiCache,
    NeighbourhoodScore,
    ReraComplaint,
    ReraProject,
    ScraperRun,
    ZoningData,
)
from .enums import (
    PG_FLATMATE_TYPES,
    AuctionSource,
    BookingStatus,
    BugSeverity,
    BugStatus,
    BugType,
    ComplaintNature,
    ConversationApp,
    ConversationSource,
    ConversationStatus,
    DocumentType,
    ExpenseCategory,
    ExperienceLevel,
    FlatmatesMode,
    FlatmatesProfileStatus,
    GazetteType,
    HotspotType,
    ImageCategory,
    InspectionType,
    LeaseStatus,
    ListingGenderPreference,
    ListingSharingType,
    MaintenanceCategory,
    MaintenanceRequestStatus,
    MaintenanceUrgency,
    ManagedPropertyStatus,
    MessageType,
    PageFormat,
    PaymentStatus,
    PropertyPurpose,
    PropertyStatus,
    PropertyType,
    RentChargeStatus,
    ScraperStatus,
    SwipeAction,
    SwipeTargetType,
    TenantStatus,
    TourStatus,
    TourVisibility,
    UserMatchStatus,
    UserReportReason,
    UserReportStatus,
    UserRole,
    VisitContext,
    VisitStatus,
    WorkOrderStatus,
)
from .payments import PaymentMethod
from .pm_documents import Document
from .pm_finance import Expense, RentCharge, RentPayment
from .pm_inspections import InspectionChecklist
from .pm_leases import Lease
from .pm_maintenance import MaintenanceRequest
from .pm_tenants import RentalApplication, RentalApplicationForm
from .properties import Amenity, Property, PropertyAmenity, PropertyImage, Visit
from .social import (
    AppCatalog,
    FlatmateProfileViewEvent,
    FlatmateSuperLikeUsage,
    MatchQnAAnswer,
    UserBlock,
    UserMatch,
    UserReport,
)
from .tours import (
    AIJob,
    CacheEntry,
    CustomDomain,
    FloorPlan,
    Hotspot,
    MediaFile,
    Scene,
    SearchIndex,
    Tour,
    TourAnalyticsEvent,
    TourBranding,
    TourLocation,
    UserSession,
    VideoMetadata,
)
from .users import User, UserSearchHistory, UserSwipe

__all__ = [
    # Users
    "User",
    "UserSearchHistory",
    "UserSwipe",
    # Agents
    "Agent",
    "AgentInteraction",
    # Bookings
    "Booking",
    # Payments
    "PaymentMethod",
    # Core
    "BugReport",
    "Page",
    "AppVersion",
    "FAQ",
    # Properties
    "Property",
    "PropertyImage",
    "Amenity",
    "PropertyAmenity",
    "Visit",
    # Blogs
    "BlogCategory",
    "BlogTag",
    "BlogPost",
    "BlogPostCategory",
    "BlogPostTag",
    # Property Management
    "Document",
    "RentalApplicationForm",
    "RentalApplication",
    "Lease",
    "RentCharge",
    "RentPayment",
    "Expense",
    "MaintenanceRequest",
    "InspectionChecklist",
    # 360 Virtual Tours
    "Tour",
    "Scene",
    "Hotspot",
    "TourAnalyticsEvent",
    "AIJob",
    "MediaFile",
    "UserSession",
    "TourLocation",
    "SearchIndex",
    "CacheEntry",
    "FloorPlan",
    "TourBranding",
    "CustomDomain",
    "VideoMetadata",
    # AI Conversations
    "AIConversation",
    "AIConversationMessage",
    # Generic conversations (all apps)
    "Conversation",
    "ConversationParticipant",
    "Message",
    # Shared social primitives
    "UserMatch",
    "FlatmateSuperLikeUsage",
    "UserBlock",
    "UserReport",
    "AppCatalog",
    "MatchQnAAnswer",
    "FlatmateProfileViewEvent",
    # Data Hub
    "CircleRate",
    "ReraProject",
    "BankAuction",
    "AuctionAlert",
    "BankRate",
    "JamabandiCache",
    "ZoningData",
    "ColonyApproval",
    "GazetteNotification",
    "ReraComplaint",
    "CourtAuction",
    "NeighbourhoodScore",
    "ScraperRun",
    # Enums
    "AuctionSource",
    "BookingStatus",
    "BugSeverity",
    "BugStatus",
    "BugType",
    "ComplaintNature",
    "ConversationApp",
    "ConversationSource",
    "ConversationStatus",
    "DocumentType",
    "ExpenseCategory",
    "ExperienceLevel",
    "FlatmatesMode",
    "FlatmatesProfileStatus",
    "GazetteType",
    "HotspotType",
    "ImageCategory",
    "InspectionType",
    "LeaseStatus",
    "ListingGenderPreference",
    "ListingSharingType",
    "MaintenanceCategory",
    "MaintenanceRequestStatus",
    "MaintenanceUrgency",
    "ManagedPropertyStatus",
    "MessageType",
    "PageFormat",
    "PaymentStatus",
    "PG_FLATMATE_TYPES",
    "PropertyPurpose",
    "PropertyStatus",
    "PropertyType",
    "RentChargeStatus",
    "ScraperStatus",
    "SwipeAction",
    "SwipeTargetType",
    "TenantStatus",
    "TourStatus",
    "TourVisibility",
    "UserMatchStatus",
    "UserReportReason",
    "UserReportStatus",
    "UserRole",
    "VisitContext",
    "VisitStatus",
    "WorkOrderStatus",
]
